#!/bin/zsh

red="\033[31m"
green="\033[32m"
bold="\033[1m"
reset="\033[0m"

TYPE=$1
FILE=$2
url="https://www.acmicpc.net/problem/$FILE"

if [[ -z $TYPE ]]; then
  echo
  echo "  Example usage:"
  echo "    create [Type] [Filename]"
  echo
  echo "    Available Types: py, cpp, js"
  exit 1
fi

if [[ ! "$TYPE" =~ ^(py|cpp|js)$ ]]; then
  echo
  echo "${bold}${red}ERROR${reset} invalid type:"
  echo
  echo "  create ${green}[py]${reset} [FILE_NAME]"
  echo "  create ${green}[cpp]${reset} [FILE_NAME]"
  echo "  create ${green}[js]${reset} [FILE_NAME]"
  exit 1
fi

if [[ -z $FILE ]]; then
  echo
  echo "${bold}${red}ERROR${reset} filename must be provided:"
  echo
  echo "  create $1 ${green}[FILE_NAME]${reset}"
  exit 1
fi

function create_file() {
  _file="$1.$2"
  _template="$PWD/templates/template"
  if [[ -f $_file ]]; then
    echo -e "${red}The file already exist.${reset}"
    code $_file
    exit 1
  fi
  [[ $2 == "cpp" ]] && echo -e "// $url\n" >"$_file"
  [[ $2 == "py" ]] && echo -e "# $url\n" >"$_file"
  [[ $2 == "js" ]] && echo -e "// $url\n" >"$_file"
  cat "$_template.$2" >>"$_file"
  code "$_file"
  echo -e "${green}Create a file successfully!${reset}"
}

filename="$PWD/src/$FILE"
if [[ "$TYPE" == "py" ]]; then
  create_file $filename py
elif [[ "$TYPE" == "cpp" ]]; then
  create_file $filename cpp
elif [[ "$TYPE" == "js" ]]; then
  create_file $filename js
fi

# open -a "Google Chrome" $url
